title: That. Just. Happened.
description: A product of contemplation
author: 
  name: Brad Turner,
  email: youremailaddress@example.com,
  url: https://brandnameboredom.github.io/
source_link: https://brandnameboredom.github.io/
